---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-expose
  namespace: default
  labels:
    app: redis-service
spec:
  ports:
  - name: redis-service
    protocol: TCP
    port: 31707
    targetPort: 6379
    nodePort: 31707
  selector:
    app: redis-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-service
  clusterIP: None
  selector:
    app: redis-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: redis-service
spec:
  serviceName: "redis-service"
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: redis-service
        image: redis:3.0
        ports:
        - containerPort: 6379
  podManagementPolicy: "Parallel"